Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [6]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

Evenly spaced numbers.


In [11]:
np.linspace(0, 5, 100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

Identity Matrix

In [12]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [13]:
np.random.rand(5)

array([ 0.95469223,  0.11387967,  0.44769084,  0.91984658,  0.51800163])

In [14]:
np.random.rand(5,4)

array([[ 0.97660065,  0.13446813,  0.61154854,  0.24417234],
       [ 0.99584927,  0.53985127,  0.60073767,  0.35814131],
       [ 0.59328542,  0.30328995,  0.59604099,  0.86569895],
       [ 0.70049388,  0.21542094,  0.91273969,  0.37262417],
       [ 0.30108625,  0.3725114 ,  0.40884079,  0.97873207]])

In [17]:
np.random.randn(4, 4)

array([[-0.17236997,  0.06592513, -0.96696548, -0.58607966],
       [-0.59434068,  2.9359061 ,  0.00875695, -0.66987562],
       [ 0.88377912,  1.04554148, -2.15909589, -0.85255577],
       [-1.08489875,  0.86245977,  0.51720194,  0.13077065]])

In [18]:
np.random.randint(1, 100) #Radom number between 1 and 100

68

In [19]:
np.random.randint(1, 100, 10 ) 

array([48, 28, 41, 52, 36, 87, 44, 40, 76, 39])

In [20]:
arr = np.arange(25)

In [23]:
randarr = np.random.randint(0, 50, 10)

In [24]:
randarr

array([40,  3, 39,  8,  6, 10, 47, 16, 37, 47])

In [25]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
randarr.max()

47

In [28]:
randarr.min()

3

In [29]:
randarr

array([40,  3, 39,  8,  6, 10, 47, 16, 37, 47])

In [30]:
randarr.argmax()

6

In [31]:
randarr.argmin()

1

In [32]:
arr.shape

(25,)

In [35]:
arr.reshape(5,5).shape

(5, 5)

In [37]:
arr.dtype

dtype('int64')

In [39]:
from numpy.random import randint

In [40]:
randint(2, 10)

3

In [41]:
arr = np.arange(0, 11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[7]

7

In [44]:
arr[0:5] = 100

In [45]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [46]:
slice_of_arr = arr[0:6]

In [48]:
slice_of_arr[:]

array([100, 100, 100, 100, 100,   5])

In [49]:
slice_of_arr[:] = 99

In [50]:
arr_copy = arr.copy()

In [51]:
arr = np.arange(25)

In [55]:
arr = arr.reshape(5, 5)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
arr[2,2]

12

In [57]:
arr[2][2]

12

In [58]:
arr[:2, 1:] #Everything upto row 2 and columns from 1

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [59]:
bool_arr = arr > 5

In [60]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [61]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [62]:
arr_2d = np.arange(50).reshape(5,10)

In [63]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
arr = np.arange(0, 11)

In [65]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [66]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [67]:
arr * 100 

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [68]:
1 / 0

ZeroDivisionError: division by zero

In [70]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [72]:
np.max(arr)

10

In [73]:
arr.max()

10

In [74]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [75]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])